### ISSUE TITLE
[3.4] 컨텍스트와 DI

### ISSUE THREAD

**Issue by HJ-Woo** [Spring-Study-20210220/spring#17]
## 정리
정리한 내용을 자유롭게 적어주세요.  
- 1.1.1 User  
  

## 발표자료
발표 자료 혹은 참고할만한 링크가 있는 경우엔 아래와 같이 첨부해주세요.
[발표 자료 예시](https://github.com/Spring-Study-20210220/spring/files/6113456/1.8.pptx)

**Comment by murane** [comment]
## 3.4.1 JdbContext의 분리

UserDao의 메소드가 클라이언트고 익명 내부클래스로 만들어지는 전략을 사용하며 jdbcContextWithStatementStrategt() 메소드는 컨텍스트이다. 다른 Dao에서도 사용할 수있게 분리해보자...

### 클래스 분리

JdbcContext라는 이름의 클래스로 컨텍스트 메소드를 옮겨 분리한다. 이렇게 하면 Datasource는 Userdao가 아닌 JdbcConext에 필요하기 때문에 이를 DI받을수있도록 한다. workWithStatementStrategy 메소드는 동일하게 

그리고 UserDao는 jdbcConext를 DI로 주입받으며 각각의 query에 따라 jdbcContext의 workwithStatementStrategy에 익명내부클래스로 전략을 생성하여 인자로 넘긴다

### 빈 의존관계 변경

UserDao는 이제 JdbcContext에 의존하게된다. 그런데 이때 JdbcContext는 인터페이스가 아닌 구체 클래스이다.. 스프링 DI는 기본적으로 인터페이스를 사이에 두고 의존클래스를 바꿔쓰는게 목적이지만.. 이ㅈ경우에는 독립적인 JDBC 컨텍스트를 제공해주는 오브젝트로서 의미가 있고 구현이 바뀔 가능성은 없다

## 3.4.2 JdbcContext의 특별한 DI

DI를 사용하긴 하지만 UserDao와 JdbcContext클래스는 클래스레벨에서 의존관계가 결정된다.

### 스프링 빈으로 DI

DI의 기본 의도에 맞게 JdbcContext의 메소드를 인터페이스로 뽑아내어 정의해두고 UserDao에서 사용하게 해야하나?? 이건 개취.... 엄밀하게는 의존관계의 고정을 막고 주입하는것이 맞지만 제어권한ㅇ을 위임했다는 IoC개념을 포괄하기때문에 DI의 기본은 따르고 있다고 볼 수 있다.

인터페이스를 적용하지 않았지만 DI구조로 만들어야 할 이유가 있을까??

JdbcContext가 스프링 IoC 컨테이너가 관리하는 싱글톤빈이 된다는 점이다.. datasource 변수는 읽기전용이므로 싱글톤으로 등록되어 공유해 사용하는것이 이상적이다. 둘째는 JdbcContext가 DI를 통해 다른 빈에 의존하기 때문이다.. DataSource를 주입받아야하기 때문에... 주입되는 객체와 주입받는 객체 모두 빈으로 등록되야한다... 이렇게 하는건 클래스는 구분되어있지만 둘이 강한 응집도를 가지기 때문이다..

이럴경우 인터페이스를 굳이 안두고 강한 결합으로 싱글톤과 DI를 위해 빈으로 등록해도 좋다.

### 코드를 이용하는 수동 DI

JdbcContext를 빈등록하여 DI하는대신 사용할 수있는 방법은 UserDao내부에 직접 DI를 적용하는 것이다. 이러면 싱글톤으로 만드는 것을 포기해야 한다...이러면 Dao내부에 하나씩의 컨텍스트를 두게 된다..

빈등록을 하지 않으므로 생성과 초기화를 누군가가 책임져야 한다... 이럴때 하나의 방법은 UserDao에게 DI까지 맡기는것이다.. 따라서 의존 객체인 DataSource를 대신 주입받고 초기화해주면 된다.

이렇게 하면 긴밀한 관계인 DAO클래스와 JdbcContext를 분리하지 않고 내부에서 사용하면서 DI를 적용할 수있다는 점이다..

전자는 실제 의존관계가 명확하게 드러나지만 DI를 엄격하게 지키지 않고 구체적인 클래스간의 관계가 노출되는 단점이 있다.

후자는 컨텍스트가 내부에서 생성되고 사용되면서 DI를 사용하기 때문에 관계를 외부에 드러나지 않는 장점이 있지만 컨텍스트를 다른 객체가 사용하면 싱글톤이 아니라 중복이 발생하며 DI를 위한 부가 작업이 필요하다는 단점이 있다. 장단을 확실히 파악하고 사용하는것이 좋으다... 애매하면 차라리 인터페이스 만들어서 평범한 DI구조로 만드는게 나을 수도 있다.

[발표자료](https://docs.google.com/presentation/d/1hWH5BnmXYdWC5ohFSymjpBBzG2n6eVFZoJ97rcUevcw/edit?usp=sharing)
