### ISSUE TITLE
[1.3] DAO의 확장

### ISSUE THREAD

**Issue by HJ-Woo** [Spring-Study-20210220/spring#3]
## 정리
정리한 내용을 자유롭게 적어주세요.  
- 1.1.1 User  
  

## 발표자료
발표 자료 혹은 참고할만한 링크가 있는 경우엔 아래와 같이 첨부해주세요.
[발표 자료 예시](https://github.com/Spring-Study-20210220/spring/files/6113456/1.8.pptx)

**Comment by murane** [comment]
[dao의 확장](https://www.notion.so/murane/1-3-DAO-b2478373fd034be89ae0fcf441603382)
