### ISSUE TITLE
[2.1] USERDAOTEST 다시보기

### ISSUE THREAD

**Issue by HJ-Woo** [Spring-Study-20210220/spring#9]
## 정리
정리한 내용을 자유롭게 적어주세요.  
- 1.1.1 User  
  

## 발표자료
발표 자료 혹은 참고할만한 링크가 있는 경우엔 아래와 같이 첨부해주세요.
[발표 자료 예시](https://github.com/Spring-Study-20210220/spring/files/6113456/1.8.pptx)

**Comment by murane** [comment]
[UserDaoTest 다시보기](https://www.notion.so/murane/2-1-UserDaoTest-2056e685695b430ebf431dc64c7208e9)
